language: python

python:
    - "3.6.3"

services:
    - postgresql

before_script:
   - psql -c 'create database travis_ci_test;' -U postgres

test:
    adapter: postgresql
    database: travis_ci_test

install:
    - pip install -r requirements.txt
    - pip install codecov

script:
    - coverage run manage.py diary/tests

env:
    - TRAVIS_SECURE_ENV_VARS = true

after_success:
  - codecov